variables:
  LC_ALL: "en_US.UTF-8"
  LANG: "en_US.UTF-8"
  GIT_STRATEGY: clone
  GIT_CHECKOUT: "true"

stages:
  - prebuild
  - build
  - test
  - deploy
  - release
  - gopublic

include:
  - project: 'Trustee/walletinternals'
    ref: refactor2
    file: '/gitlabcicd/wallet-gitlab-ci.yml'
